### ISSUE TITLE
Request for release tag

### ISSUE THREAD

**Issue by joshuakraemer** [novomesk/qt-jpegxl-image-plugin#14]
Could you please consider adding a release tag? I would like to package your plugin for Void Linux (draft PR at https://github.com/void-linux/void-packages/pull/31397), which requires a release version.

**Comment by novomesk** [comment]
I can do it after libjxl release new version. The plugin already uses some features added after last libjxl release.

**Comment by novomesk** [comment]
https://github.com/novomesk/qt-jpegxl-image-plugin/releases/tag/v0.2.0
