### ISSUE TITLE
[Question] How to uninstall?

### ISSUE THREAD

**Issue by hidden-r4d** [novomesk/qt-jpegxl-image-plugin#19]
Is there a way to uninstall this before or after installing a new version of kimageformat-plugins which enables jpeg xl support?

**Comment by novomesk** [comment]
It is enough to delete `libqjpegxl.so` (or `libqjpegxl5.so`).

It is usually installed in one of the following folders:

- /usr/lib64/qt5/plugins/imageformats
- /usr/lib/qt/plugins/imageformats/
- /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats

There could be also `jxl.desktop` in `/usr/share/kservices5/qimageioplugins/`

kimageformats will install the same jxl.desktop file.
