### ISSUE TITLE
Add instructions to the README on enabling jpegxl support in Digikam.

### ISSUE THREAD

**Issue by AndersonIsaac** [novomesk/qt-jpegxl-image-plugin#20]
Built, installed, worked like a charm in gwenview. But not with Digikam.  Someone who's struggling with this may benefit. Skimmed settings interface and here is the answer (It is not consistent with other Qt apps to require jxl to be enabled manually. What is the reasoning behind this, I wonder):

Settings -> Configure digikam -> Views -> Mime Types, add "jxl" (without brackets) to the Additional image file extensions field.
Now the jxl thumbnails should be displayed properly (you can try to add the jpegxl-logo.jxl from testfiles to digikam to test this right away).

**Comment by novomesk** [comment]
Future digiKam will enable extension by default:
https://www.reddit.com/r/kde/comments/tau3k6/next_digikam_770_will_support_avifaom_image/
