### ISSUE TITLE
Plugin built with libjxl v0.9.1 doesn't work [msys2]

### ISSUE THREAD

**Issue by eddiezato** [novomesk/qt-jpegxl-image-plugin#27]
I'm building qimgv/yacreader along with this plugin in msys2/ucrt64 and msys2/clang64 environments. If the plugin is based on libjxl v0.8.2, it works fine, but if libjxl v0.9.1, the apps simply can't recognize jxl images.

**Comment by novomesk** [comment]
I tried MSYS2  CLANG64 + Qt6.

I used qmake6.exe and slightly changed the .pro script and for me it worked:

![image](https://github.com/novomesk/qt-jpegxl-image-plugin/assets/52529860/e96fb19f-9238-4336-9f8b-bbb872524b0e)

**Comment by eddiezato** [comment]
I build with cmake and Qt 6.6.1. I don't see any errors. But v0.9.1 just doesn't work, as if the plugin doesn't there at all. And v0.8.2 works fine.

**Comment by eddiezato** [comment]
Apparently I've been hasty again in creating the issue. 😅
Found a new dependency that was missing, `libjxl_cms.dll`.
