### ISSUE TITLE
qjpegxl6.dll (Dec 19, 2023) appears to not work with YACReader Qt6

### ISSUE THREAD

**Issue by MusashiMiyamoto** [novomesk/qt-jpegxl-image-plugin#28]
When placing qjpegxl.dll (Dec 19, 2023) into C:\Program Files\YACReader\imageformats\ - and using this build:
https://github.com/YACReader/yacreader/releases/download/9.14.1/YACReader-v9.14.1.2402053-winx64-7z.exe
Comics containing .jxl images open correctly.

When placing qjpegxl6.dll (Dec 19, 2023) into C:\Program Files\YACReader\imageformats\ - and using this build:
https://github.com/YACReader/yacreader/releases/download/9.14.1/YACReader-v9.14.1.2402053-winx64-7z-qt6.exe
Comics containing .jxl open with an error message.

This may not be an issue on your end at all, but perhaps you or someone else knows why this is.

Of course, for now, it is easy enough to simply use the combination above which does work.

Thank you to anyone able to provide any assistance.

**Comment by novomesk** [comment]
The reason is probably that the plug-in DLL was built using Qt 6.5.3 but YACReader using older 6.3.1

The plugin needs to use the same Qt version or older to work with the app.

**Comment by MusashiMiyamoto** [comment]
Not knowing much about Qt, I erroneously assumed it may be the case that a v6 Qt app would be compatible with any v6.x.x plugin, whereas only a different major version (3.x.x, 4.x.x, 5.x.x, for example) would not. So, this is not the case. 
Thank you.

**Comment by novomesk** [comment]
In this archive I have a plug-in which works in Qt6 Win64 YACReader

https://github.com/novomesk/qt-jpegxl-image-plugin/releases/download/v0.6.2/plugin_for_qt6_2_4.zip
