### ISSUE TITLE
Failed decode

### ISSUE THREAD

**Issue by Orum** [novomesk/qt-jpegxl-image-plugin#3]
For some images, the results are _very_ different from those from djxl.  See example attached file (zipped because GitHub doesn't permit .jxl).
[output.zip](https://github.com/novomesk/qt-jpegxl-image-plugin/files/5756566/output.zip)

Command used to create it: `cjxl input.png  output.jxl -m -Q 25 -s 9 -E 3 --noise=1 --lossy-palette --palette=0  --num_threads 16 -v`

**Comment by novomesk** [comment]
Can you send me your **input.png** ?

When I decode the output.jxl using djxl I get this:
![decoded_djxl](https://user-images.githubusercontent.com/52529860/103403775-a5248400-4b51-11eb-97e2-d08dd6aa94b8.png)
and output.jxl decoded via my plug-in it looks like this:
![Screenshot_20201231_101009](https://user-images.githubusercontent.com/52529860/103403811-c4bbac80-4b51-11eb-8c96-b9f9a68c0757.png)

**Comment by Orum** [comment]
Whoops, I ran it again and now get the same results from djxl as the plugin.  I think I accidentally decoded a different image (the test image was encoded several times) with djxl, and thought it was working with djxl.  The problem seems to lie in the encoder when using some of those flags, and not in the decoding.

Sorry for the noise.
