### ISSUE TITLE
Cannot view image dimension on dolphin's file properties.

### ISSUE THREAD

**Issue by arun54321** [novomesk/qt-jpegxl-image-plugin#9]
![image](https://user-images.githubusercontent.com/42943340/111565899-2fc86700-87c2-11eb-8016-d732f4fa0569.png)

It doesn't show width and height for avif and jxl.

**Comment by novomesk** [comment]
I don't know from where dolphin takes the information now but I have a feeling that it is not related to my plug-in. Probably the support has to be added elsewhere.

**Comment by arun54321** [comment]
Okay.

**Comment by novomesk** [comment]
I believe [KFileMetaData](https://invent.kde.org/frameworks/kfilemetadata) is the place where support could be added, if someone contribute extractor for JXL files.

If the support is available in [exiv2](https://github.com/Exiv2/exiv2), then KFileMetaData could add support easily. AVIF is going to be supported in future exiv2 v0.27.4

**Comment by ghost** [comment]
Exiv2 now supports JXL/bmff (Exiv2/exiv2@a750ea27809efd6db838f4a753ad4acd9eb17cc1).

To view the dimension (and other metadata) of JXL (and AVIF, HEIF, etc.) files:
1. Build Exiv2 from latest git commit (Remember to set `-DEXIV2_ENABLE_BMFF=On`)
2. Apply [this diff](https://github.com/jo620kix/kfilemetadata/commit/46b0a628a12ab51d3ebf911db32d79fcd2e22ab3.diff) to kfilemetadata
